name: Deploy web app
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - working-directory: ./cedar-playground-wasm
        run: wasm-pack build --target web
      - working-directory: ./cedar-playground
        run: yarn install --immutable --immutable-cache --check-cache
      - working-directory: ./cedar-playground
        run: yarn build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./cedar-playground/dist/cedar-playground
          single-commit: true